[package]
name = "med_proj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
derive = "1.0.0"
rand = "0.8.5"
serde = { version = "1.0.201", features = ["derive"] }
structopt = "0.3.26"
